# Generated by Django 2.2 on 2019-04-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0002_auto_20190418_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(default='', max_length=20),
        ),
    ]
