# Generated by Django 2.2 on 2019-04-20 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0004_auto_20190420_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='addr',
            field=models.CharField(default='三里屯', max_length=128),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP01.Publisher'),
        ),
    ]
