# Generated by Django 2.2 on 2019-04-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0005_auto_20190420_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(default='123', max_length=20),
        ),
    ]
