# Generated by Django 2.2 on 2019-04-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0006_auto_20190421_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mname', models.CharField(max_length=20)),
                ('intro', models.TextField()),
                ('time', models.CharField(max_length=20)),
                ('yingting', models.CharField(max_length=20)),
            ],
        ),
    ]
