# Generated by Django 2.2 on 2019-04-22 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0007_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('intro', models.TextField()),
                ('price', models.IntegerField()),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP01.Goods_type')),
            ],
        ),
    ]
