# Generated by Django 2.2 on 2019-04-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0010_admininfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='email',
            field=models.CharField(default='', max_length=20),
        ),
    ]
