# Generated by Django 2.2 on 2019-04-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0011_admininfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='huiyuan',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
