# Generated by Django 2.2 on 2019-04-30 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0011_admininfo_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Huiyuan',
        ),
    ]
