# Generated by Django 2.2 on 2019-04-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0012_huiyuan_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='huiyuan',
            old_name='data',
            new_name='creat_time',
        ),
    ]
