# Generated by Django 2.2 on 2019-04-30 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0013_huiyuan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Huiyuan',
            new_name='Huiyuan2',
        ),
    ]
