# Generated by Django 2.2 on 2019-04-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0013_auto_20190430_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huiyuan',
            name='creat_time',
            field=models.DateTimeField(),
        ),
    ]
