# Generated by Django 2.2 on 2019-04-30 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0015_auto_20190430_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huiyuan',
            name='creat_time',
        ),
    ]
