# Generated by Django 2.2 on 2019-04-30 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0015_huiyuan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Huiyuan2',
        ),
    ]
