# Generated by Django 2.2 on 2019-04-30 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0016_remove_huiyuan_creat_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admininfo',
            name='email',
        ),
    ]
