# Generated by Django 2.2 on 2019-04-30 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0016_delete_huiyuan2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Huiyuan',
        ),
    ]
