# Generated by Django 2.2 on 2019-04-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0020_delete_admininfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('pwd', models.CharField(default='123', max_length=20)),
                ('email', models.CharField(default='123', max_length=20)),
            ],
        ),
    ]
