# Generated by Django 2.2 on 2019-04-30 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0022_huiyuan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminInfo',
        ),
        migrations.DeleteModel(
            name='Huiyuan',
        ),
    ]
